
services:
  - type: web
    name: linkedin-api-serpapi
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: SERPAPI_KEY
        sync: false
